### ISSUE TITLE
Bug in Parametric Diagram

### ISSUE THREAD

**Issue by dianelid** [eduardoafs/sysadl#20]
Parametric diagram doesn't show constraint equation.

<img width="578" alt="bug parametric diagram" src="https://user-images.githubusercontent.com/34031964/37401466-e07fd296-2766-11e8-86f5-0e6203a07116.png">

**Comment by eduardoafs** [comment]
For some reason, Sirius isn't recognizing the services in this version. Check it out.

**Comment by eduardoafs** [comment]
Commit 6367431 fixed it, waiting for merge.
