### ISSUE TITLE
Output Parameters in Action

### ISSUE THREAD

**Issue by dianelid** [eduardoafs/sysadl#35]
Should not allow adding more than one output parameter in Actions.

**Comment by eduardoafs** [comment]
Closed. An action should not have more than one return parameter.

**Comment by dianelid** [comment]
After creating the Action and clicking "_Parameter (Out)_" a window with the desired output parameter types is displayed. After selecting the parameter nothing happens visually, but the .aird file is changed and the project cannot be saved. This window should not even appear, as it should not accept more than one input parameter.

**Comment by eduardoafs** [comment]
Solved by commit 4db42c8
